const supplies = [
    { id: 0, nombre: 'Cartulina verde lm²', stock: 10 },
    { id: 1, nombre: 'Papel bond A4', stock: 50 },
    { id: 2, nombre: 'Tinta para impresora', stock: 5 },
    { id: 3, nombre: 'Lápices de grafito', stock: 100 },
    { id: 4, nombre: 'Borradores', stock: 30 },
    { id: 5, nombre: 'Reglas de plástico', stock: 20 },
    { id: 6, nombre: 'Marcadores permanentes', stock: 15 },
    { id: 7, nombre: 'Cinta adhesiva', stock: 25 },
    { id: 8, nombre: 'Tijeras', stock: 10 },
    { id: 9, nombre: 'Grapas', stock: 200 },
    { id: 10, nombre: 'Clips', stock: 300 },
    { id: 11, nombre: 'Pegamento en barra', stock: 40 },
    { id: 12, nombre: 'Carpetas de archivo', stock: 50 },
    { id: 13, nombre: 'Sobres manila', stock: 60 },
    { id: 14, nombre: 'Post-it', stock: 70 },
    { id: 15, nombre: 'Calculadoras', stock: 10 },
    { id: 16, nombre: 'Cajas de archivo', stock: 20 },
    { id: 17, nombre: 'Resaltadores', stock: 30 },
    { id: 18, nombre: 'Pilas AA', stock: 50 },
    { id: 19, nombre: 'Cable de red', stock: 15 },
    { id: 20, nombre: 'Adaptadores USB', stock: 10 },
    { id: 21, nombre: 'Mouse inalámbrico', stock: 5 },
    { id: 22, nombre: 'Teclados', stock: 8 },
    { id: 23, nombre: 'Monitores', stock: 4 },
    { id: 24, nombre: 'Impresoras', stock: 3 },
    { id: 25, nombre: 'Cartuchos de tinta', stock: 12 },
    { id: 26, nombre: 'Papel fotográfico', stock: 25 },
    { id: 27, nombre: 'Cables HDMI', stock: 10 },
    { id: 28, nombre: 'Discos duros externos', stock: 7 },
    { id: 29, nombre: 'Memorias USB', stock: 20 },
    { id: 30, nombre: 'Router WiFi', stock: 5 }
];

export default supplies;
