// src/supplies.js
const supplies = [
    { code: 'M0001', name: 'Cartulina verde lm²', quantity: 10 },
    { code: 'M0002', name: 'Papel bond A4', quantity: 50 },
    { code: 'M0003', name: 'Tinta para impresora', quantity: 5 },
    { code: 'M0004', name: 'Lápices de grafito', quantity: 100 },
    { code: 'M0005', name: 'Borradores', quantity: 30 },
    { code: 'M0006', name: 'Reglas de plástico', quantity: 20 },
    { code: 'M0007', name: 'Marcadores permanentes', quantity: 15 },
    { code: 'M0008', name: 'Cinta adhesiva', quantity: 25 },
    { code: 'M0009', name: 'Tijeras', quantity: 10 },
    { code: 'M0010', name: 'Grapas', quantity: 200 },
    { code: 'M0011', name: 'Clips', quantity: 300 },
    { code: 'M0012', name: 'Pegamento en barra', quantity: 40 },
    { code: 'M0013', name: 'Carpetas de archivo', quantity: 50 },
    { code: 'M0014', name: 'Sobres manila', quantity: 60 },
    { code: 'M0015', name: 'Post-it', quantity: 70 },
    { code: 'M0016', name: 'Calculadoras', quantity: 10 },
    { code: 'M0017', name: 'Cajas de archivo', quantity: 20 },
    { code: 'M0018', name: 'Resaltadores', quantity: 30 },
    { code: 'M0019', name: 'Pilas AA', quantity: 50 },
    { code: 'M0020', name: 'Cable de red', quantity: 15 },
    { code: 'M0021', name: 'Adaptadores USB', quantity: 10 },
    { code: 'M0022', name: 'Mouse inalámbrico', quantity: 5 },
    { code: 'M0023', name: 'Teclados', quantity: 8 },
    { code: 'M0024', name: 'Monitores', quantity: 4 },
    { code: 'M0025', name: 'Impresoras', quantity: 3 },
    { code: 'M0026', name: 'Cartuchos de tinta', quantity: 12 },
    { code: 'M0027', name: 'Papel fotográfico', quantity: 25 },
    { code: 'M0028', name: 'Cables HDMI', quantity: 10 },
    { code: 'M0029', name: 'Discos duros externos', quantity: 7 },
    { code: 'M0030', name: 'Memorias USB', quantity: 20 }
];

export default supplies;