const util_nuevo = [
    { util_id: 0, name: 'Cartulina verde lm²', stock: 10 },
    { util_id: 1, name: 'Papel bond A4', stock: 50 },
    { util_id: 2, name: 'Tinta para impresora', stock: 5 },
    { util_id: 3, name: 'Lápices de grafito', stock: 100 },
    { util_id: 4, name: 'Borradores', stock: 30 },
    { util_id: 5, name: 'Reglas de plástico', stock: 20 },
    { util_id: 6, name: 'Marcadores permanentes', stock: 15 },
    { util_id: 7, name: 'Cinta adhesiva', stock: 25 },
    { util_id: 8, name: 'Tijeras', stock: 10 },
    { util_id: 9, name: 'Grapas', stock: 200 },
    { util_id: 10, name: 'Clips', stock: 300 },
    { util_id: 11, name: 'Pegamento en barra', stock: 40 },
    { util_id: 12, name: 'Carpetas de archivo', stock: 50 },
    { util_id: 13, name: 'Sobres manila', stock: 60 },
    { util_id: 14, name: 'Post-it', stock: 70 },
    { util_id: 15, name: 'Calculadoras', stock: 10 },
    { util_id: 16, name: 'Cajas de archivo', stock: 20 },
    { util_id: 17, name: 'Resaltadores', stock: 30 },
    { util_id: 18, name: 'Pilas AA', stock: 50 },
    { util_id: 19, name: 'Cable de red', stock: 15 },
    { util_id: 20, name: 'Adaptadores USB', stock: 10 },
    { util_id: 21, name: 'Mouse inalámbrico', stock: 5 },
    { util_id: 22, name: 'Teclados', stock: 8 },
    { util_id: 23, name: 'Monitores', stock: 4 },
    { util_id: 24, name: 'Impresoras', stock: 3 },
    { util_id: 25, name: 'Cartuchos de tinta', stock: 12 },
    { util_id: 26, name: 'Papel fotográfico', stock: 25 },
    { util_id: 27, name: 'Cables HDMI', stock: 10 },
    { util_id: 28, name: 'Discos duros externos', stock: 7 },
    { util_id: 29, name: 'Memorias USB', stock: 20 },
    { util_id: 30, name: 'Router WiFi', stock: 5 }
];

export default util_nuevo;
