const util_nuevo = [
    { util_id: 0, name: 'Cartulina verde lm²', stock: 8 },
    { util_id: 1, name: 'Papel bond A4', stock: 7 },
    { util_id: 2, name: 'Cuadernos rayados', stock: 6 },
    { util_id: 3, name: 'Lápices de grafito', stock: 9 },
    { util_id: 4, name: 'Borradores', stock: 5 },
    { util_id: 5, name: 'Reglas de plástico', stock: 4 },
    { util_id: 6, name: 'Marcadores permanentes', stock: 3 },
    { util_id: 7, name: 'Cinta adhesiva', stock: 6 },
    { util_id: 8, name: 'Tijeras', stock: 5 },
    { util_id: 9, name: 'Grapas', stock: 8 },
    { util_id: 10, name: 'Clips', stock: 7 },
    { util_id: 11, name: 'Pegamento en barra', stock: 9 },
    { util_id: 12, name: 'Carpetas de archivo', stock: 6 },
    { util_id: 13, name: 'Sobres manila', stock: 4 },
    { util_id: 14, name: 'Post-it', stock: 3 },
    { util_id: 15, name: 'Resaltadores', stock: 5 },
    { util_id: 16, name: 'Tempera', stock: 8 },
    { util_id: 17, name: 'Pinceles', stock: 7 },
    { util_id: 18, name: 'Cartucheras', stock: 6 },
    { util_id: 19, name: 'Crayones', stock: 9 },
    { util_id: 20, name: 'Colores de madera', stock: 5 },
    { util_id: 21, name: 'Plastilina', stock: 4 },
    { util_id: 22, name: 'Papel crepé', stock: 3 },
    { util_id: 23, name: 'Papel de seda', stock: 6 },
    { util_id: 24, name: 'Papel lustre', stock: 5 },
    { util_id: 25, name: 'Hojas de colores', stock: 8 },
    { util_id: 26, name: 'Papel cuadriculado', stock: 7 },
    { util_id: 27, name: 'Papel milimetrado', stock: 9 },
    { util_id: 28, name: 'Goma Eva', stock: 6 },
    { util_id: 29, name: 'Pegamento líquido', stock: 4 },
    { util_id: 30, name: 'Sacapuntas', stock: 3 },
    { util_id: 31, name: 'Compás', stock: 5 },
    { util_id: 32, name: 'Esquemas didácticos', stock: 8 },
    { util_id: 33, name: 'Pegatinas', stock: 7 },
    { util_id: 34, name: 'Tijeras de punta redonda', stock: 6 },
    { util_id: 35, name: 'Stickers educativos', stock: 9 },
    { util_id: 36, name: 'Láminas de aprendizaje', stock: 4 },
    { util_id: 37, name: 'Cuadernos cuadriculados', stock: 3 },
    { util_id: 38, name: 'Bolígrafos de colores', stock: 5 },
    { util_id: 39, name: 'Hojas bond blancas', stock: 6 }
];

export default util_nuevo;